---
- hosts:
    - Debian
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade packages
      ansible.builtin.apt:
        state: latest

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot machine if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes


    - name: Ensure nginx.service is running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - nginx.service
      when: inventory_hostname in groups['ngnix']


    - name: Ensure apache is running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - apache2
      when: inventory_hostname in groups['apache']


    - name: Ensure PowerDNS is running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - pdns.service
      when: inventory_hostname in groups['DNS_auth']


    - name: Ensure mariaDB is running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - mariadb.service
      when: inventory_hostname in groups['mariadb']


    - name: Ensure postgres is running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - postgres.service
      when: inventory_hostname in groups['postgres']

    - name: Esnure unbound container is running
      community.docker.docker_container:
        name: "{{ item }}"
        state: started
        restart_policy: always
      loop:
        - unbound-dns
      when: inventory_hostname in groups['DNS_resolver']


    - name: Esnure traefik container is running
      community.docker.docker_container:
        name: "{{ item }}"
        state: started
        restart_policy: always
      loop:
        - traefik
      when: inventory_hostname in groups['traefik']


    - name: Ensure docker is running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - docker.service
      when: inventory_hostname in groups['docker']

    - name: Esnure minecraft container is running
      community.docker.docker_container:
        name: "{{ item }}"
        state: started
        restart_policy: always
      loop:
        - mcserver
        - minecraft-bluemap-1
      when: inventory_hostname in groups['minecraft']


    - name: Ensure Proxmox services are running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - pve-guests.service
        - system-pve\x2dcontainer.slice
        - pve-firewall-commit.service
        - pve-query-machine-capabilities.service
        - pve-ha-lrm.service
        - pvefw-logger.service
        - etc-pve.mount
        - pve-firewall.service
        - pve-storage.target
        - mnt-pve-nasDisk.mount
        - pve-lxc-syscalld.service
        - pve-sdn-commit.service
        - pvedaemon.service
        - pve-cluster.service
        - pvescheduler.service
        - pveproxy.service
        - pvestatd.service
      when: inventory_hostname in groups['pve']




    
